### ISSUE TITLE
Where i can set my google map api key?

### ISSUE THREAD

**Issue by d3c0b81f** [madisona/django-google-maps#14]
![untitled2](https://cloud.githubusercontent.com/assets/19824363/17455521/4eb76c3a-5bd3-11e6-88da-0987b81b821f.png)

**Comment by madisona** [comment]
Thanks for your message. Google has apparently changed things a bit relatively recently for new projects.  

I just published a new version 0.5.0  that allows/requires you to put a "GOOGLE_MAPS_API_KEY" in your settings file. Also, I removed the 'sensor=false' as it isn't required anymore.
