### ISSUE TITLE
Error:  uncaught exception: unknown (can't convert to string)

### ISSUE THREAD

**Issue by dscapuano** [madisona/django-google-maps#17]
django 1..8.7
django-google-maps 0.5
python 2.7.12

On entering a new address, get the above error in Javascript.

**Comment by madisona** [comment]
Hi @dscapuano Can you post a screen shot of the address you're entering and the javascript trace?

**Comment by dscapuano** [comment]
Very strange results. 
1.  I entered and address and after a bit it worked while I was fiddling with firebug. 
2.  A couple of tries thereafter it did not work and returned the uncaught exception error.  
3.  I closed the tab I was using in Firefox and reopened it.  I tried the same address and it worked.  No other address worked and returned the uncaught exception error.
BTW.  I am not an expert in Javascript or debugging in a browser.  I could not get a stack trace.  Attached are two files.  One shows a very cool 3d of Lower Manhattan (I used to work there).  The  other shows that an object was added to the DB.  When I look at the DB (Sqlite3), there is the address I entered, but no geocodes.
Don't know if this helps, but thanks,
dc

**Comment by madisona** [comment]
@dscapuano I haven't been able to re-produce that behavior... it works just fine for me. let me know if you continue to have issues. There is a sample app included in this repo which is what I'm using to test it.

**Comment by dscapuano** [comment]
I believe this has to do with Google Maps not accepting calls from 
localhost.  I am testing on Linux 14.4x and using the standard Django 
runserver.  I have a key that works with Google if called from 
Javascript.  It doesn't seem to work otherwise.
I have looked everwhere for a solution to this, but none of them seem to 
work.  Google's documentation is confusing or non-existant.
dc

**Comment by madisona** [comment]
and what version of django are you using? Could there be any plugins messing with the javascript inadvertently? Let me know if you have anything more to try to diagnose. Without reproducing the issue or anyone else having the issue, I'm not sure there's much I can do to help you look into it.

**Comment by dscapuano** [comment]
Django==1.8.7

**Comment by madisona** [comment]
sorry, I can't seem to reproduce any strange behavior.
