### ISSUE TITLE
Migrate to django 1.11

### ISSUE THREAD

**Issue by ppeczek** [madisona/django-google-maps#21]
Django 1.11 admin throws an error for GoogleMapsAddressWidget.
Code:
```
    formfield_overrides = {
        map_fields.AddressField: {'widget': map_widgets.GoogleMapsAddressWidget},
    }
```
Error:
```
build_attrs() got an unexpected keyword argument 'type'
```
Django 1.10 admin works well

**Comment by madisona** [comment]
Thanks @ppeczek   I just pushed out a version 0.7.0 that is compatible with Django 1.11

Django fundamentally changed the widget rendering to make it far simpler to customize widgets. Because of this though, the new version is only compatible with Django 1.11+
