### ISSUE TITLE
"Geocode was not successful because of the following reason":  ERROR

### ISSUE THREAD

**Issue by mykljohn** [madisona/django-google-maps#23]
I'm trying to test this out and I get the above error.

I'm on Python 2.7, Django 1.11

**Comment by madisona** [comment]
Can you post any more info?  And do you have `GOOGLE_MAPS_API_KEY = '<SAMPLE_KEY>'` set to an appropriate value in your settings?

**Comment by mykljohn** [comment]
Sure, 
yes I have my API key.

in my model:
    address = map_fields.AddressField(max_length=200)
    location = map_fields.GeoLocationField(max_length=200)

in admin:
    formfield_overrides = {
        map_fields.AddressField: {'widget': map_widgets.GoogleMapsAddressWidget},
    }

The Admin screen comes up and displays the fields and the map in Satellite view (can I change that and center it on a location?)  When I enter a city name, it popups that error msg.

**Comment by madisona** [comment]
the project expects to update a field `#id_geolocation`.  It looks like you named the field `location` in your model.

You can try either changing the field name to be `geolocation` or explicitly set the html id to be `id_geolocation`.

**Comment by mykljohn** [comment]
ah ok, same problem.  New model:
    address = map_fields.AddressField(max_length=200)
    geolocation = map_fields.GeoLocationField(max_length=200)

**Comment by madisona** [comment]
what is the address you're trying to geocode?

**Comment by mykljohn** [comment]
I just put in the city "Queretaro" without quotes :)

**Comment by mykljohn** [comment]
and I tried New York...same thing

**Comment by madisona** [comment]
do you get the same result if you just pull down the `django-google-maps` project and run the included sample application included?  

I just pulled it down and ran the sample app without issues on python 27 and django 1.11. both "New York" and "Queretaro" behave as I'd expect.

**Comment by mykljohn** [comment]
Sorry, I'll try it this weekend.
