### ISSUE TITLE
How can we use this app in forms.py ?

### ISSUE THREAD

**Issue by trDjango** [madisona/django-google-maps#24]
Hello Madisona;
how can we use this application in forms.py, not admin.py?

**Comment by madisona** [comment]
You just override the widget like the admin sample is doing, but on your ModelForm class... 
https://docs.djangoproject.com/en/dev/topics/forms/modelforms/#overriding-the-default-fields

You also need to make sure in your template you include {{form.media}}. (the admin does that automatically)
