### ISSUE TITLE
Using Maps for frontend users in templates

### ISSUE THREAD

**Issue by MUDASSARHASHMI** [madisona/django-google-maps#39]
Hi,
I've seen your previous post related to this issue but still not able to make it work for templates.

Following are the details what I am trying to do:

     `from django.db import models
      from django_google_maps import fields as map_fields

    class Address(models.Model):
        address = map_fields.AddressField(max_length=200)
        geolocation = map_fields.GeoLocationField(max_length=200)

        def __unicode__(self):
            return `self.address````
My Forms.py:

    `from django_google_maps import widgets as map_widgets
     from django_google_maps import fields as map_fields

    class AddressForm(forms.ModelForm):
        class Meta:
            model = Address
            fields = ['address', 'geolocation']
            formfield_overrides = {
                map_fields.AddressField: {'widget': map_widgets.GoogleMapsAddressWidget},
            }`
My Views.py:
    from .forms import AddressForm
    from django.views.generic.edit import FormView

    class MapView(FormView):
        form_class = AddressForm
        template_name = 'address.html'
        # success_url = '/thanks/'

        def form_valid(self, form):

            return super(MapView, self).form_valid(form)
    I am working with Python 2.7, Django 1.11.

    Finally Template:
    `{% extends 'base.html' %}
    {{form.media}}

    {% block content %}
    <div class="container">
        <div class="row">
            <div class="col-4 offset-3">
            <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Send message" />
            </form>
            </div>
        </div>
    </div>
    {% endblock content %}
`
I've tried {{ form.media }} in my head in base.html and in template itself directly by removing it from base to avoid any duplication but still map is not showing up in frontend template. I got the both fields displaying fine and there is also no error in chrome inspect elements. My GoogleAPI key is listed in settings.py as per your instructions.

I've collected static and in my urls.py I am serving static locally.

    `from customer.views import (
        MapView
     )

    from django.conf import settings
    from django.conf.urls.static import static
    urlpatterns = [
         url(r'^$', views.home, name='home'),
         url(r'^map/', MapView.as_view(), name='map'),
         url(r'^admin/', admin.site.urls),
     ]
    if settings.DEBUG:
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

`
Your advise will be much appreciated if you can clearly help to identify the problem.

**Comment by madisona** [comment]
Hi @MUDASSARHASHMI - The `formfield_overrides` is only for the django admin. Use `widgets` instead like this:

```
class SampleForm(forms.ModelForm):

    class Meta(object):
        model = SampleModel
        fields = ['address', 'geolocation']
        widgets = {
            "address": GoogleMapsAddressWidget,
        }
```

https://docs.djangoproject.com/en/dev/topics/forms/modelforms/#overriding-the-default-fields

**Comment by MUDASSARHASHMI** [comment]
This still not working as you proposed. Tried in Django 2.0 and Django 1.11 with Python2.7 and 3.5. Thank your for your response though.

**Comment by madisona** [comment]
If you pull down the master branch, there's a working example at the index url
