### ISSUE TITLE
Making geolocation read only returns world map

### ISSUE THREAD

**Issue by orschiro** [madisona/django-google-maps#4]
![djangoGoogleMaps](https://f.cloud.github.com/assets/170947/33466/8b6a517e-5092-11e2-8e43-523d3955a224.png)
Hello,

I followed your suggestion and put geolocation into read only.

```
from locations.models import Container
from django.contrib import admin
from django_google_maps import widgets as map_widgets
from django_google_maps import fields as map_fields

class ContainerAdmin(admin.ModelAdmin):
    formfield_overrides = {
        map_fields.AddressField: {'widget': map_widgets.GoogleMapsAddressWidget},
    }
    readonly_fields=('geolocation',)

admin.site.register(Container, ContainerAdmin)
```

However, now I only see the world map in the admin but no longer the exact address as given by AddressField.

How can I fix that?

Regards

Robert

**Comment by tatvaparthesh** [comment]
What does map_fields.GeoLocationField actually is?
