### ISSUE TITLE
Plan on Django3

### ISSUE THREAD

**Issue by ramonyaskal** [madisona/django-google-maps#59]
Are you planning to do support Django3 ?

**Comment by madisona** [comment]
version 0.12.0 just released supports Django3

**Comment by ramonyaskal** [comment]
ERROR: django-google-maps 0.12.0 has requirement Django<3,>=1.11, but you'll have django 3.0.2 which is incompatible.

**Comment by madisona** [comment]
@ramonyaskal Sorry, I forgot to change the requirements file. Try version 0.12.1 I just put out there

**Comment by ramonyaskal** [comment]
@madisona thank you very much for your work
