### ISSUE TITLE
Is there an example (or step to step tutorial) on how to use it?

### ISSUE THREAD

**Issue by f3rn4nd0000** [madisona/django-google-maps#72]
Hi, 

Forgive my unenlightenment, i'm quite new to Django and web development in general, but i searched thoroughly through the official docs (https://pypi.org/project/django-google-maps/) , stackoverflow and other sources, cloned this repo and i'm beating my head trying to figure out on how this works, there's a sample folder inside this repo should i execute virtual environment inside of  it?
I ran a local instance of the project using virtual environment, what i did was go to the main project folder and executed the following through bash (Obviously i added my API key to settings.py).
I'm also in doubt if i should  reproduce all the steps contained in README file. Because this repo already have for example the models.py files,  etc.

```
virtualenv -p python3 venv
source venv/bin/activate
cd requirements
pip install -r requirements.txt
pip install -r test.txt
python manage.py migrate
cd $HOME/django-google-maps/django-google-maps-master && source ./venv/bin/activate && python manage.py runserver 0.0.0.0:8800
```
Currently i'm trying to figure out what is wrong because it actually renders the map for quite a few milliseconds then it disappears sugesting me to look at the JavaScript Console
![gonewrong](https://user-images.githubusercontent.com/42982873/110150130-a0808400-7dbd-11eb-9e5d-b02f9b88eeb4.png)

Thanks for your time!

**Comment by madisona** [comment]
@f3rn4nd0000 did you look at the javascript console? Usually something like this would have to do with not having a maps api key set properly, or an invalid key.

**Comment by kushraj1204** [comment]
@madisona Hi there, I was wondering if I could use it for forms outside of the django admin. It is currently rendering plain text input fields with address and comma separated geoposition values. I have used it in the django-admin quite easily but can't seem to figure it out working it in the front end.
