### ISSUE TITLE
Having only the 'address' field in the form.py breaks the search in a template

### ISSUE THREAD

**Issue by iamsashank09** [madisona/django-google-maps#75]
I am trying to display the address autofill in the template, using the example code in the sample app. 

But I need only the 'address' field and not the 'geolocation' field in my template, as I want the user to enter just the location in a search box. 

Simply put, just an input box for the address, no map and no geolocation box. 

So, when I remove the 'geolocation' from the fields in the forms.py, it breaks the address box as well. If I add 'geolocation' back, it works fine again.

forms.py code:

> `from django.forms import ModelForm
> from .models import Rental
> from django_google_maps.widgets import GoogleMapsAddressWidget
> import json
> 
> class mapForm(ModelForm):
>     class Meta:
>         model = Rental
>         fields = ['address']
>         widgets = {
>             "address": GoogleMapsAddressWidget(attrs={
>       'data-autocomplete-options': json.dumps({ 'types': ['geocode',
>       'establishment'], 'componentRestrictions': {
>                   'country': 'ind'
>               }
>           })
>       }),
>         }`

model.py code:

> `from django.db import models
> 
> from django_google_maps import fields as map_fields
> 
> class Rental(models.Model):
>     address = map_fields.AddressField(max_length=200)
>     geolocation = map_fields.GeoLocationField(max_length=100)   
> `

index.html:

> `<html>
>     <head>
>         {{form.media}}
>     </head>
>     {{form.as_p}}
> </html>`

Error I see in the console:

> jquery.min.js:2 Uncaught TypeError: Cannot read property 'value' of null
>     at Object.getExistingLocation (google-maps-admin.js:105)
>     at Object.initialize (google-maps-admin.js:41)
>     at HTMLDocument.<anonymous> (google-maps-admin.js:178)
>     at j (jquery.min.js:2)
>     at k (jquery.min.js:2)

Can someone please help me out here?
Thank you.

**Comment by madisona** [comment]
@iamsashank09  - if you don't want the geolocation field to show, just make it a hidden field.  The geolocation is important, and is used to save off the location so it doesn't need to be re-looked up every time you draw the map.

**Comment by iamsashank09** [comment]
@madisona Thanks for your quick response. I used HiddenInput() to hide the 'geolocation' field and it is working well.

Any idea on how I can hide the Map as well? I require only the search box. Hope there is a way to do that too. 

Thank you @madisona !

**Comment by madisona** [comment]
@iamsashank09 it sounds go me like maybe what you're really interested in is just the auto-complete behavior?  If so, I'd recommend you work directly with the Google API used:  https://developers.google.com/maps/documentation/javascript/places-autocomplete

Here is where it is used in this project: https://github.com/madisona/django-google-maps/blob/master/django_google_maps/static/django_google_maps/js/google-maps-admin.js#L60
