### ISSUE TITLE
Django 4.0 force_text

### ISSUE THREAD

**Issue by quantal-dev-ml** [madisona/django-google-maps#88]
django==4.0.2
django-google-maps==0.12.4

ImportError: cannot import name 'force_text' from 'django.utils.encoding'

**Comment by ronaldlangeveld** [comment]
This has been fixed in the Repo, however it hasn't been updated on Pypi. For now just copy the the app into your django project from the repo.

**Comment by Moon-developer** [comment]
Came here to mention the same issue. Will download for now, any ETA on a release?

**Comment by madisona** [comment]
I apologize for the delay - a release is shipping now v0.13.0
