### ISSUE TITLE
Widget template renders improperly inside a div

### ISSUE THREAD

**Issue by esbc-disciple** [madisona/django-google-maps#92]
I'm wondering what the repercussions would be to omit `class="map_canvas_wrapper"` from the HTML of django_google_maps/templates/django_google_maps/widgets/map_widget.html. 

That div has some padding built into it such that it overflows parent divs. It looks real bad on desktop. However... looks perfect on mobile (iOS, Safari).

I'm willing to do further research, but I cannot find the map_widget.html code to change it once it's pip-installed. I don't know if it gets compiled into some other template.

![image](https://github.com/madisona/django-google-maps/assets/96537894/e9fed25f-3d33-416b-b402-433e4dd6440e)

By the way, you're the best for writing this app. Blessed of the Lord.

**Comment by madisona** [comment]
Hi @esbc-disciple - you could accomplish this in a few ways. I think the simplest would be to override the css using your own rule. In your own css file, add a more specific target.  The existing css is here: https://github.com/madisona/django-google-maps/blob/master/django_google_maps/static/django_google_maps/css/google-maps-admin.css


Or, you could override the template altogether if you wanted. It is a form template, and should be able to be overridden similar to this:  https://docs.djangoproject.com/en/4.2/ref/forms/renderers/#overriding-built-in-widget-templates
